# Generated by Django 3.2.13 on 2022-06-26 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_use', models.PositiveIntegerField(blank=True, null=True)),
                ('expiresOn', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'ترجمه رسمی'), (2, 'تولید محتوا'), (3, 'زیرنویس'), (4, 'مقاله / کتاب')], default=1)),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'صفحه'), (2, 'کلمه'), (3, 'ترم'), (4, 'تعداد'), (5, 'دقیقه')])),
                ('base_price', models.PositiveIntegerField()),
                ('stamp_option', models.PositiveSmallIntegerField(choices=[(1, 'None'), (3, 'MFA'), (2, 'MOJ'), (4, 'MOJ + MFA')], default=1)),
                ('pickup_option', models.PositiveSmallIntegerField(choices=[(1, 'In Person'), (2, 'Peyk'), (3, 'Online')], default=3)),
                ('stamp_moj_price', models.PositiveIntegerField(default=0)),
                ('stamp_mfa_price', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_fa', models.CharField(max_length=250)),
                ('is_source', models.BooleanField(default=True)),
                ('is_destination', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'ترجمه رسمی'), (2, 'تولید محتوا'), (3, 'زیرنویس'), (4, 'مقاله / کتاب')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Not Paid'), (3, 'Pending'), (4, 'In Progress'), (5, 'Done')], default=1)),
                ('delivery_option', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Fast'), (3, 'Urgent')], default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_language', to='order.language')),
                ('to_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_language', to='order.language')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=order.models.generate_filename)),
                ('ext_id', models.UUIDField(default=uuid.uuid4)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('stamp', models.PositiveSmallIntegerField(choices=[(1, 'None'), (3, 'MFA'), (2, 'MOJ'), (4, 'MOJ + MFA')], default=1)),
                ('pickup', models.PositiveSmallIntegerField(choices=[(1, 'In Person'), (2, 'Peyk'), (3, 'Online')], default=3)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'In Progress'), (4, 'Done')], default=1)),
                ('count', models.PositiveIntegerField()),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('asignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.discount')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.doctype')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.order')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.upload')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('gateway', models.PositiveSmallIntegerField(choices=[(1, 'SEP')], default=1)),
                ('recipt', models.CharField(blank=True, max_length=300, null=True)),
                ('tid', models.CharField(blank=True, max_length=300, null=True)),
                ('card', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('trace', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Failed'), (3, 'Pending'), (4, 'Success')], default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('priority', models.SmallIntegerField(default=0)),
                ('items', models.ManyToManyField(blank=True, to='order.DocType')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
